### ISSUE TITLE
Issu with "npm start"

### ISSUE THREAD

**Issue by judemont** [bchiang7/v4#250]
Hello, 

When I run `npm start` I have this error : 

`⠋ Compiling Gatsby Functions
/home/judemont/projet/web/my-website-2/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/judemont/projet/web/my-website-2/node_modules/webpack/lib/util/createHash.js:144:18)
    at BulkUpdateDecorator.digest (/home/judemont/projet/web/my-website-2/node_modules/webpack/lib/util/createHash.js:79:21)
    at Compilation.createHash (/home/judemont/projet/web/my-website-2/node_modules/webpack/lib/Compilation.js:3449:47)
    at /home/judemont/projet/web/my-website-2/node_modules/webpack/lib/Compilation.js:2469:39
    at /home/judemont/projet/web/my-website-2/node_modules/webpack/lib/Compilation.js:2670:5
    at Object.eachLimit (/home/judemont/projet/web/my-website-2/node_modules/neo-async/async.js:3461:14)
    at Compilation._runCodeGenerationJobs (/home/judemont/projet/web/my-website-2/node_modules/webpack/lib/Compilation.js:2632:12)
    at Compilation.codeGeneration (/home/judemont/projet/web/my-website-2/node_modules/webpack/lib/Compilation.js:2618:8)
    at /home/judemont/projet/web/my-website-2/node_modules/webpack/lib/Compilation.js:2454:11
    at eval (eval at create (/home/judemont/projet/web/my-website-2/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/judemont/projet/web/my-website-2/node_modules/webpack/lib/optimize/ModuleConcatenationPlugin.js:454:31
    at processTicksAndRejections (node:internal/process/task_queues:77:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0
`

**Comment by Weetile** [comment]
Same issue here.

**Comment by 0xapurv** [comment]
That is due node version.
Downgrade to Node version 16, it'll work flawlessly!

**Comment by judemont** [comment]
Okay, thanks.
